### ISSUE TITLE
Copilot Cannot Set a Copilot on a Challenge

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/resources-api#42]
Logged in as: **TCConnCopilot**

Values:
![Screen Shot 2020-10-21 at 12 35 19 PM](https://user-images.githubusercontent.com/5400156/96750502-ff5ad900-1399-11eb-8d02-fc47b5a4e883.png)

`POST v5/resources` Request Body:
```json
{
"challengeId": "27720d94-f172-4367-8e13-24674524461d",
"memberHandle": "jcori",
"roleId": "a83e62e0-cba4-4dfc-8522-1515cfe79d04"
}
```

403 Response:
`{"message":"Only M2M, admin or user with full access role can perform this action"}`

**Comment by rootelement** [comment]
Tested and working as an admin user.

**Comment by rootelement** [comment]
I believe this is wrong:
https://github.com/topcoder-platform/resources-api/blob/e4ad10a8236c04da1210a77a5d225624ba5b4deb/src/services/ResourceService.js#L241

I believe the logic needs to be updated to:
1. Every resource creation attempt should check to see if the resource has signed the terms for that role on that challenge.
2. If machine token, perform the action
3. If admin, perform the action
4. If not admin, check to see if the currentUser is a copilot or manager on the challenge. If so, perform the action
5. If just a regular user, check to see if they're adding themselves to a selfObtainable role

I'm not sure what scenario this If / checkAccess call would be run given the steps above:
https://github.com/topcoder-platform/resources-api/blob/e4ad10a8236c04da1210a77a5d225624ba5b4deb/src/services/ResourceService.js#L248

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/resources-api/commit/39fd74186c0d26bb84dc70b73bcc3c5fca088b88

**Comment by rootelement** [comment]
This scenario now works:
1. I create a challenge with an admin account
2. I select thomas as a copilot
3. Thomas logs in and decided sergey should review the challenge, so he selects internal reviewer and selects sergey. Thomas' JWT should be able to add a resource even though it’s not an admin.

**Comment by vikasrohit** [comment]
@rootelement @ThomasKranitsas I have another scenario which is making copilot selecting resources tricky. https://challenges.topcoder-dev.com/projects/9074/challenges/26beb2ff-b8a2-4ce8-8761-e5b17462d004/edit has a copilot resource for `TCConCopilotMgr` and I can see this record in API response when I am logged in as Admin, however, when I am logging as `TCConnCopilot` (who is actually a copilot and is part of the project team and exists as a Observer resource on the challenge), I can see only two resource records (with admin I am seeing 19 resource records) and those records are only for the `TCConnCopilot` user itself, one is for Manager role and another for `Observer` role. Now this gives impression to the `TCConnCopilot` that no copilot is selected for the challenge and he/she may attempt to change the copilot and may lead to errors because copilot resource already exists.

**Comment by rootelement** [comment]
Fixed and deployed
